version: "3.5"

networks:
  mope_net:
    external:
      name: mope

services:
  db:
    container_name: pg_container
    networks:
      mope_net:
        aliases:
          - db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mope
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    networks:
      mope_net:
        aliases:
          - sgbd
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
